<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
);
